### ISSUE TITLE
IOS 9

### ISSUE THREAD

**Issue by DanilaVladi** [nkreipke/FTPManager#23]
Most of the used API is deprecated now.

**Comment by nkreipke** [comment]
Thanks for the info. To be honest, I'd like to deprecate FTPManager too. Thing is, I can't find a good replacement (the ones I found did also rely on CFFTPStream).

I'll try to come up with a good solution for this, just give me a little time.

**Comment by DanilaVladi** [comment]
Ok, thanks!

**Comment by MattFedo** [comment]
I literally came back to this page because Xcode was yelling at me there are a ton of depreciated items in this git.  Nico, I couldnt agree more.  FTPManager has been a staple for me for the past 4 years and Ive built other managers on top of it.

Looking over at NSURLSession, it seems it might handle some FTP stuff but I dont think it is as simple as your stuff. Ill also look into upgrading the latest version to get rid of those depreciations.

**Comment by Spokane-Dude** [comment]
I have the same issue; a fix or replacement would be greatly appreciated!
